#include <stdio.h>

/*
                        ######## PROBLEM ########
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
                        ########################

    AUTHOR: Gabriel Henrique
*/

//FIBONACCI
int fib(int num)
{
    if(num == 1)
        return 1;
    if(num == 2)
        return 2;

    return fib(num-2) + fib(num-1);
}

int main()
{
    int sum,temp = 0,count = 0;

    //REQUIRE THE LIMIT NUMBER OF FIBONACCI
    printf("Sum limit number: ");
    scanf("%i", &sum);

    //FIND THE LAST FIBONACCI SUM UNDER THE LIMIT
    while(temp < sum)
    {
        temp = fib(count);
        count++;
    }

    printf("Fibonacci even-valued sum is %i", temp);
return 0;
}
